[package]
name = "whodb"
version = "0.1.0"
authors = ["Bruno Henrique - Garu <squall.bruno@gmail.com>"]
edition = "2018"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
